const slopSnippets = [
    "def is_even(n):\n    return n % 2 == 0 # Generated by AI",
    "// TODO: Ask ChatGPT how to center this div",
    "try {\n  code();\n} catch (e) {\n  askCopilot(e);\n}",
    "<!-- Hallucinating a non-existent React Hook -->\nconst [slop, setSlop] = useSlop();",
    "console.log('I have no idea how this works, but the AI said it does.');",
    "git commit -m 'AI wrote this, idk'",
    "while(true) {\n  copyPasteFromStackOverflow();\n}"
];

document.getElementById('slop-btn').addEventListener('click', () => {
    const snippet = slopSnippets[Math.floor(Math.random() * slopSnippets.length)];
    
    const slopElement = document.createElement('div');
    slopElement.className = 'generated-slop';
    slopElement.textContent = snippet;
    
    // Random position
    const x = Math.random() * (window.innerWidth - 300);
    const y = Math.random() * (window.innerHeight - 100);
    
    slopElement.style.left = `${x}px`;
    slopElement.style.top = `${y}px`;
    
    document.getElementById('slop-container').appendChild(slopElement);
    
    // Clean up after animation
    setTimeout(() => {
        slopElement.remove();
    }, 3000);
});

// Glitch effect on title
setInterval(() => {
    const title = document.querySelector('.glitch');
    if (Math.random() > 0.95) {
        title.style.transform = `translate(${Math.random() * 10 - 5}px, ${Math.random() * 10 - 5}px)`;
        setTimeout(() => {
            title.style.transform = 'translate(0, 0)';
        }, 100);
    }
}, 50);